# The main job for rag_evaluation.
resources:
  jobs:
    bot_intake_drive_scraping:
      name: bot_intake_drive_scraping
      tasks:
        - task_key: crawl_drive
          job_cluster_key: ${var.job_cluster_small}
          notebook_task:
            notebook_path: ../src/notebook/sharepoint_drive_scraping.py
            base_parameters:
              target: ${bundle.target}
              catalog: ${var.catalog}
              schema: ${var.schema}
              volume: ${var.volume}

          run_if: ALL_SUCCESS