workflow_default: &workflow_default
  name: workflow_default
  queue:
    enabled: true
  max_concurrent_runs: 1
  performance_target: PERFORMANCE_OPTIMIZED
  environments:
    - environment_key: Default
      spec:
        environment_version: "5"

task_data_intake_pipeline: &data_intake_chunks
  task_key: chunk
  environment_key: Default
  notebook_task:
    notebook_path: ../src/notebooks/chunks_data.py
    base_parameters:
      target: ${bundle.target}
      volume: ${var.volume}
      catalog: ${var.catalog}
      schema: ${var.schema}
      control_table: sharepoint_doc_control
      chunk_table: chunks
      source_data_folder: ""
      chunk_strategy: chunked
      chunk_size: 800
      chunk_overlap: 200
      min_chunk_size: 20
  run_if: ALL_SUCCESS

resources:
  jobs:
    intake_chunks:
      <<: *workflow_default
      name: intake_chunks
      tasks:
        - <<: *data_intake_chunks