workflow_default: &workflow_default
  name: workflow_default
  job_clusters:
    - job_cluster_key: job_cluster_small
      new_cluster: ${var.job_cluster_small}
  queue:
    enabled: true
  max_concurrent_runs: 1

task_data_intake_pipeline: &data_intake_chunks
  task_key: chunk_data
  job_cluster_key: ${var.job_cluster_small}
  notebook_task:
    notebook_path: ../src/notebooks/chunks_data.py
    base_parameters:
      target: ${bundle.target}
      volume: ${var.volume}
      catalog: ${var.catalog}
      schema: ${var.schema}
      control_table: sharepoint_doc_control
      chunk_table: chunks
      source_data_folder: ""
      chunk_strategy: chunked
      chunk_size: 800
      chunk_overlap: 200
      min_chunk_size: 20
  run_if: ALL_SUCCESS

resources:
  jobs:
    intake_chunks:
      <<: *workflow_default
      name: intake_chunks
      tasks:
        <<: *data_intake_chunks